# Generated by Django 4.2.5 on 2023-10-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/Disable access to', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField()),
                ('description', models.JSONField()),
                ('total_tests', models.IntegerField(default=0)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.instructor')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/Disable access to', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField()),
                ('description', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/Disable access to', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.JSONField()),
                ('variants', models.JSONField()),
                ('correct_answer', models.JSONField()),
                ('is_testing', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.instructor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/Disable access to', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_tests', models.IntegerField(default=0)),
                ('right_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.instructor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.subject'),
        ),
    ]
