# Generated by Django 4.2.5 on 2023-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='title',
        ),
        migrations.AddField(
            model_name='subject',
            name='description_ru',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='description_uz',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='title_ru',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='title_uz',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
    ]
