# Generated by Django 4.2.5 on 2023-10-09 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_remove_subject_description_remove_subject_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title',
        ),
        migrations.RemoveField(
            model_name='test',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.RemoveField(
            model_name='test',
            name='variants',
        ),
        migrations.AddField(
            model_name='section',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title_ru',
            field=models.CharField(default=str, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='title_uz',
            field=models.CharField(default=str, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='correct_answer_ru',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='correct_answer_uz',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='question_ru',
            field=models.CharField(default=str, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='question_uz',
            field=models.CharField(default=str, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='variants_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='variants_uz',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=[], size=None),
            preserve_default=False,
        ),
    ]
