# Generated by Django 4.2.6 on 2023-10-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_remove_section_description_remove_section_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='checked_tests',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='solved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
