from .admin import *
from .advertising import *
from .authentication import *
from .feedback import *
from .file import *
from .instructor import *
from .section import *
from .statistic import *
from .student import *
from .subject import *
from .test import *
from .user import *
